<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'Firehed\\Input\\Containers\\ParsedInput' => 'Containers/ParsedInput.php',
    'Firehed\\Input\\Containers\\RawInput' => 'Containers/RawInput.php',
    'Firehed\\Input\\Containers\\SafeInput' => 'Containers/SafeInput.php',
    'Firehed\\Input\\Exceptions\\InputException' => 'Exceptions/InputException.php',
    'Firehed\\Input\\Interfaces\\ParserInterface' => 'Interfaces/ParserInterface.php',
    'Firehed\\Input\\Interfaces\\URIValidationInterface' => 'Interfaces/URIValidationInterface.php',
    'Firehed\\Input\\Interfaces\\ValidationInterface' => 'Interfaces/ValidationInterface.php',
    'Firehed\\Input\\Objects\\ClientID' => 'Objects/ClientID.php',
    'Firehed\\Input\\Objects\\ClientSecret' => 'Objects/ClientSecret.php',
    'Firehed\\Input\\Objects\\ID' => 'Objects/ID.php',
    'Firehed\\Input\\Objects\\InputObject' => 'Objects/InputObject.php',
    'Firehed\\Input\\Objects\\ListOf' => 'Objects/ListOf.php',
    'Firehed\\Input\\Objects\\Rbit' => 'Objects/Rbit.php',
    'Firehed\\Input\\Objects\\String' => 'Objects/String.php',
    'Firehed\\Input\\Parsers\\JSON' => 'Parsers/JSON.php',
    'Firehed\\Input\\Parsers\\URLEncoded' => 'Parsers/URLEncoded.php',
  ),
  'function' => array(),
  'xmap' => array(
    'Firehed\\Input\\Containers\\ParsedInput' => array(
      'Firehed\\Input\\Containers\\RawInput',
      'ArrayAccess',
    ),
    'Firehed\\Input\\Containers\\SafeInput' => 'Firehed\\Input\\Containers\\ParsedInput',
    'Firehed\\Input\\Exceptions\\InputException' => 'Exception',
    'Firehed\\Input\\Interfaces\\URIValidationInterface' => 'Firehed\\Input\\Interfaces\\ValidationInterface',
    'Firehed\\Input\\Objects\\ClientID' => 'Firehed\\Input\\Objects\\ID',
    'Firehed\\Input\\Objects\\ClientSecret' => 'Firehed\\Input\\Objects\\String',
    'Firehed\\Input\\Objects\\ID' => 'Firehed\\Input\\Objects\\InputObject',
    'Firehed\\Input\\Objects\\ListOf' => 'Firehed\\Input\\Objects\\InputObject',
    'Firehed\\Input\\Objects\\Rbit' => array(
      'Firehed\\Input\\Objects\\InputObject',
      'Firehed\\Input\\Interfaces\\ValidationInterface',
    ),
    'Firehed\\Input\\Objects\\String' => 'Firehed\\Input\\Objects\\InputObject',
    'Firehed\\Input\\Parsers\\JSON' => 'Firehed\\Input\\Interfaces\\ParserInterface',
    'Firehed\\Input\\Parsers\\URLEncoded' => 'Firehed\\Input\\Interfaces\\ParserInterface',
  ),
));
