name: tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  CI: "true"

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        composer:
          # - low
          - high
        php:
          - 7.2
          - 7.3
          - 7.4
          # - 8.0

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          ini-values: zend.assertions=1, assert.exception=1
          php-version: ${{ matrix.php }}

      # TODO: build cache

      - name: Install dependencies
        run: composer install --no-interaction --no-ansi --no-progress --no-suggest --prefer-dist --optimize-autoloader
        # todo: prefer-lowest

      - name: PHPUnit
        run: vendor/bin/phpunit

      - name: Submit code coverage
        run: bash <(curl -s https://codecov.io/bash)

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        composer:
          # - low
          - high
        php:
          - 7.2
          - 7.3
          - 7.4
          # - 8.0

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          php-version: ${{ matrix.php }}

      # TODO: build cache

      - name: Install dependencies
        run: composer install --no-interaction --no-ansi --no-progress --no-suggest --prefer-dist --optimize-autoloader
        # todo: prefer-lowest

      - name: PHPStan
        run: vendor/bin/phpstan analyse --no-progress .

  # phpcs:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       composer:
  #         # - low
  #         - high
  #       php:
  #         - 7.2
  #         - 7.3
  #         - 7.4
  #         # - 8.0

  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2

  #     - name: Setup PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         coverage: xdebug
  #         php-version: ${{ matrix.php }}

  #     # TODO: build cache

  #     - name: Install dependencies
  #       run: composer install --no-interaction --no-ansi --no-progress --no-suggest --prefer-dist --optimize-autoloader
  #       # todo: prefer-lowest

  #     - name: PHPCS
  #       run: vendor/bin/phpcs src tests

